name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:

          java-version: 11
          distribution: 'temurin'
      - name: debug
        run: ls src/main/java/io/github/komet0141/
      - name: debug
        run: ls src/main/java/io/github/komet0141/simpleJson/
      - name: debug
        run: ls src/main/java/io/github/komet0141/simpleJson/JsonValue
      - name: debug
        run: ls src/main/java/io/github/komet0141/simpleJson/JsonValue/JsonPrimitive
      - name: Publish package
        run: mvn --batch-mode -e deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_IO_TOKEN }}
